In [1]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "raw"

dataset = pd.read_csv(
    DATA_DIR / "Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv"
)

dataset.head()

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [2]:
print(dataset.columns)
print("Dataset Size:", len(dataset))

Index(['flags', 'instruction', 'category', 'intent', 'response'], dtype='str')
Dataset Size: 26872

In [3]:
dataset[["instruction", "response"]].sample(10)

,instruction,response
15796,I am calling to download the bill #12588,I've decoded that you're calling to download b...
26659,help me checking if there are any updates on m...,Indeed! I understand that you're seeking assis...
14703,editing {{Account Category}} account,How exceptional it is to hear that you're inte...
23643,I have issues setting up a new delivery address,I'm sorry to hear that you're having issues se...
25378,I have got to see purchase {{Order Number}} cu...,Your message means a lot! I'm aligned with the...
22500,leaving review for a service,We appreciate your interest in leaving a revie...
5834,i do not know how to check the accepted paymen...,No worries at all! I'm here to guide you on ho...
26869,I'm waiting for a reimbjrsement of {{Currency ...,"Firstly, I genuinely understand the importance..."
8432,i dont know whatto do to talk to customer assi...,Thanks for getting in touch! I grasp that you'...
657,can ya help me cancel purchase {{Order Number}},Sure! I'm here to assist you in canceling your...

In [4]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "data" / "raw"

dataset = pd.read_csv(
    DATA_DIR / "Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv"
)

print(dataset.shape)
dataset.head()

(26872, 5)

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [5]:
dataset = dataset[["instruction", "response"]]

dataset.head()

,instruction,response
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...

In [6]:
dataset.columns = ["question", "answer"]

dataset.head()

,question,answer
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...

In [7]:
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

PROCESSED_DIR.mkdir(exist_ok=True)

dataset.to_csv(
    PROCESSED_DIR / "chat_dataset.csv",
    index=False
)

print("Dataset saved!")

Dataset saved!